name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€

on: 
   release:
      branches: 
         - '![0-9]+.[0-9]+.[0-9]+-dev'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job-test was automatically triggered by a ${{ github.event_name }} event."